export const availableDeliveriesData = [
  {
    orderId: "ORD-1001",
    username: "Andi Pratama",
    address:
      "Apartemen Permata Hijau Tower B, Lt. 12 No. 18, Jl. Melati No. 12, Kebayoran Lama, Jakarta Selatan",
    lat: -6.244534,
    long: 106.800621,
    status: "pickup",
  },
  {
    orderId: "ORD-1002",
    username: "Siti Rahma",
    address: "Jl. Cempaka Putih No. 8, Cempaka Putih Barat, Jakarta Pusat",
    lat: -6.174923,
    long: 106.865012,
    status: "delivery",
  },
  {
    orderId: "ORD-1003",
    username: "Budi Santoso",
    address:
      "Cluster Green Antasari Residence Blok C3 No. 20, Jl. Pangeran Antasari, Jakarta Selatan",
    lat: -6.260123,
    long: 106.797334,
    status: "pickup",
  },
  {
    orderId: "ORD-1004",
    username: "Rina Kurnia",
    address: "Jl. Sunter Agung No. 44, Sunter Jaya, Jakarta Utara",
    lat: -6.146723,
    long: 106.867442,
    status: "delivery",
  },
  {
    orderId: "ORD-1005",
    username: "Fajar Nugroho",
    address: "Ruko Grogol Square Blok A2 No. 5, Jl. Grogol Raya, Jakarta Barat",
    lat: -6.170513,
    long: 106.783222,
    status: "pickup",
  },
  {
    orderId: "ORD-1006",
    username: "Maya Sari",
    address:
      "Jl. Kelapa Gading Boulevard, Kompleks Gading Kirana Blok D5, Jakarta Utara",
    lat: -6.15613,
    long: 106.90702,
    status: "delivery",
  },
  {
    orderId: "ORD-1007",
    username: "Rizky Maulana",
    address: "Tebet Barat Dalam I No. 7, Tebet, Jakarta Selatan",
    lat: -6.23145,
    long: 106.850142,
    status: "pickup",
  },
  {
    orderId: "ORD-1008",
    username: "Dewi Anggraini",
    address: "Perumahan Rawamangun Muka Indah Blok B1 No. 10, Jakarta Timur",
    lat: -6.187854,
    long: 106.891563,
    status: "delivery",
  },
  {
    orderId: "ORD-1009",
    username: "Hendra Wijaya",
    address: "Jl. Duri Kepa No. 9, Kebon Jeruk, Jakarta Barat",
    lat: -6.18022,
    long: 106.773441,
    status: "pickup",
  },
  {
    orderId: "ORD-1010",
    username: "Lina Marlina",
    address: "Jl. Pasar Minggu Raya No. 3, Pancoran, Jakarta Selatan",
    lat: -6.264901,
    long: 106.837721,
    status: "delivery",
  },
];

export const ongoingDeliveryData = {
  orderId: "ORD-1001",
  username: "Andi Pratama",
  address:
    "Apartemen Permata Hijau Tower B, Lt. 12 No. 18, Jl. Melati No. 12, Kebayoran Lama, Jakarta Selatan",
  lat: -6.244534,
  long: 106.800621,
  status: "pickup",
  currentStatus: "PICKUP_AT_USER",
};

export const deliveryHistory = [
  {
    orderId: "ORD-1001",
    customerName: "Andi Pratama",
    address: "Jl. Melati No. 12, Jakarta Selatan",
    deliveryStatus: "Completed",
    deliveryDateTime: "2025-11-24 14:30",
    pickupDateTime: "2025-11-24 12:00",
    numberOfItems: 10,
    totalWeight: "5 kg",
    distance: "3 km",
    duration: "25 min",
    proofImages: ["proof1.jpg", "proof2.jpg"],
  },
  {
    orderId: "ORD-1002",
    customerName: "Siti Rahma",
    address: "Jl. Cempaka Putih No. 8, Jakarta Pusat",
    deliveryStatus: "Completed",
    deliveryDateTime: "2025-11-23 16:00",
    pickupDateTime: "2025-11-23 13:30",
    numberOfItems: 7,
    totalWeight: "3.2 kg",
    distance: "5 km",
    duration: "35 min",
    proofImages: ["proof3.jpg"],
  },
  {
    orderId: "ORD-1003",
    customerName: "Budi Santoso",
    address: "Jl. Pangeran Antasari No. 55, Jakarta Selatan",
    deliveryStatus: "Late",
    deliveryDateTime: "2025-11-22 15:20",
    pickupDateTime: "2025-11-22 12:50",
    numberOfItems: 12,
    totalWeight: "6.5 kg",
    distance: "4 km",
    duration: "40 min",
    proofImages: ["proof4.jpg", "proof5.jpg"],
  },
  {
    orderId: "ORD-1004",
    customerName: "Rina Kurnia",
    address: "Jl. Sunter Agung No. 44, Jakarta Utara",
    deliveryStatus: "Completed",
    deliveryDateTime: "2025-11-21 11:45",
    pickupDateTime: "2025-11-21 09:30",
    numberOfItems: 5,
    totalWeight: "2.5 kg",
    distance: "2 km",
    duration: "15 min",
    proofImages: ["proof6.jpg"],
  },
  {
    orderId: "ORD-1005",
    customerName: "Fajar Nugroho",
    address: "Jl. Grogol Raya No. 21, Jakarta Barat",
    deliveryStatus: "Completed",
    deliveryDateTime: "2025-11-20 17:10",
    pickupDateTime: "2025-11-20 14:50",
    numberOfItems: 9,
    totalWeight: "4.8 kg",
    distance: "6 km",
    duration: "45 min",
    proofImages: ["proof7.jpg"],
  },
  {
    orderId: "ORD-1006",
    customerName: "Maya Sari",
    address: "Jl. Kelapa Gading Boulevard, Jakarta Utara",
    deliveryStatus: "Completed",
    deliveryDateTime: "2025-11-19 13:00",
    pickupDateTime: "2025-11-19 10:30",
    numberOfItems: 8,
    totalWeight: "4 kg",
    distance: "5 km",
    duration: "30 min",
    proofImages: ["proof8.jpg"],
  },
  {
    orderId: "ORD-1007",
    customerName: "Rizky Maulana",
    address: "Jl. Tebet Barat Dalam No. 7, Jakarta Selatan",
    deliveryStatus: "Completed",
    deliveryDateTime: "2025-11-18 15:40",
    pickupDateTime: "2025-11-18 13:10",
    numberOfItems: 11,
    totalWeight: "5.5 kg",
    distance: "4 km",
    duration: "35 min",
    proofImages: ["proof9.jpg", "proof10.jpg"],
  },
  {
    orderId: "ORD-1008",
    customerName: "Dewi Anggraini",
    address: "Jl. Rawamangun Muka No. 10, Jakarta Timur",
    deliveryStatus: "Completed",
    deliveryDateTime: "2025-11-17 12:20",
    pickupDateTime: "2025-11-17 09:50",
    numberOfItems: 6,
    totalWeight: "3 kg",
    distance: "3 km",
    duration: "20 min",
    proofImages: ["proof11.jpg"],
  },
  {
    orderId: "ORD-1009",
    customerName: "Hendra Wijaya",
    address: "Jl. Duri Kepa No. 9, Jakarta Barat",
    deliveryStatus: "Late",
    deliveryDateTime: "2025-11-16 16:15",
    pickupDateTime: "2025-11-16 13:40",
    numberOfItems: 10,
    totalWeight: "5 kg",
    distance: "5 km",
    duration: "40 min",
    proofImages: ["proof12.jpg"],
  },
  {
    orderId: "ORD-1010",
    customerName: "Lina Marlina",
    address: "Jl. Pasar Minggu Raya No. 3, Jakarta Selatan",
    deliveryStatus: "Completed",
    deliveryDateTime: "2025-11-15 14:50",
    pickupDateTime: "2025-11-15 12:20",
    numberOfItems: 7,
    totalWeight: "3.5 kg",
    distance: "4 km",
    duration: "30 min",
    proofImages: ["proof13.jpg"],
  },
];

export enum DeliveryStage {
  PICKUP_AT_USER = "PICKUP_AT_USER",
  PICKUP_AT_STORE = "PICKUP_AT_STORE",
  DELIVERY_AT_STORE = "DELIVERY_AT_STORE",
  DELIVERY_AT_DESTINATION = "DELIVERY_AT_DESTINATION",
}

export const buttonLabel: Record<DeliveryStage, string> = {
  PICKUP_AT_USER: "Mark as Picked Up",
  PICKUP_AT_STORE: "Finish Pickup",
  DELIVERY_AT_STORE: "Mark as Collected",
  DELIVERY_AT_DESTINATION: "Mark as Delivered",
};

export const deliveryStatus: Record<DeliveryStage, string> = {
  PICKUP_AT_USER: "Pick up at user",
  PICKUP_AT_STORE: "Finish Pickup",
  DELIVERY_AT_STORE: "Mark as Collected",
  DELIVERY_AT_DESTINATION: "Mark as Delivered",
};


